services:
  dhcp-relay:
    image: go-dhcp-relay:local
    networks:
      underlay:
        ipv4_address: 10.1.255.150
      vlan4000:
        ipv4_address: 10.255.0.3
    volumes:
      - ./dhcp-relay:/etc/go-dhcp-relay

  dhcp-server:
    image: dhcp-server:local
    privileged: true
    networks:
      underlay:
        ipv4_address: 10.1.255.2

  dhcp-client:
    image: dhcp-client:local
    privileged: true
    networks:
      - vlan4000

networks:
  vlan4000:
    ipam:
      config:
        - subnet: 10.255.0.0/24

  underlay:
    ipam:
      config:
        - subnet: 10.1.255.0/24
